# Generated by Django 3.0.7 on 2022-09-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_hospital',
            fields=[
                ('ID_PS', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=40)),
                ('Especialidad', models.CharField(default='No Aplica', max_length=40)),
                ('Tipo_personal', models.CharField(choices=[('M', 'Medico(a)'), ('E', 'Enfermera(o)'), ('A', 'Auxiliar')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ID_User', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=40)),
                ('Contraseña', models.CharField(max_length=8)),
                ('Tipo_Usuarios', models.CharField(choices=[('M', 'Medico(a)'), ('E', 'Enfermera(o)'), ('A', 'Auxiliar'), ('P', 'Paciente')], default='P', max_length=1)),
            ],
        ),
    ]
