# Generated by Django 3.0.7 on 2022-09-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idPaciente', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=35)),
                ('apellidos', models.CharField(max_length=35)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('fechaNacimiento', models.DateField()),
                ('edad', models.CharField(max_length=3)),
                ('RH', models.CharField(max_length=2)),
                ('correo', models.EmailField(max_length=35)),
                ('celular', models.CharField(max_length=35)),
                ('direccion', models.CharField(max_length=35)),
                ('ciudad', models.CharField(max_length=35)),
                ('estado', models.BooleanField(default=True)),
                ('nombreFamiliar', models.CharField(max_length=35)),
                ('parentescoFamiliar', models.CharField(max_length=35)),
                ('correoFamiliar', models.EmailField(max_length=35)),
                ('celularFamiliar', models.CharField(max_length=35)),
            ],
        ),
        migrations.RenameModel(
            old_name='Personal_hospital',
            new_name='Personal',
        ),
    ]
