# Generated by Django 3.0.7 on 2022-09-05 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academical', '0002_auto_20220905_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='estado',
            new_name='internado',
        ),
    ]
