# Generated by Django 3.0.7 on 2022-09-05 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academical', '0003_auto_20220905_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('IDSV', models.AutoField(primary_key=True, serialize=False)),
                ('fechaSV', models.DateTimeField()),
                ('presionArterial', models.IntegerField(max_length=3)),
                ('oximetria', models.IntegerField(max_length=3)),
                ('frecuenciaRespiratoria', models.IntegerField(max_length=3)),
                ('frecuenciaCardiaca', models.IntegerField(max_length=3)),
                ('glicemias', models.IntegerField(max_length=3)),
                ('IDPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academical.Paciente')),
            ],
        ),
    ]
