# Generated by Django 3.0.7 on 2022-09-08 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academical', '0004_signosvitales'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='ID_UserP',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Academical.Usuario'),
        ),
        migrations.AddField(
            model_name='personal',
            name='ID_UserPS',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Academical.Usuario'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellidos',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='celular',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='celularFamiliar',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ciudad',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='correo',
            field=models.EmailField(max_length=45),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='correoFamiliar',
            field=models.EmailField(max_length=45),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombreFamiliar',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='parentescoFamiliar',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='personal',
            name='Especialidad',
            field=models.CharField(default='No Aplica', max_length=45),
        ),
        migrations.AlterField(
            model_name='personal',
            name='Nombre',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Nombre',
            field=models.CharField(max_length=45),
        ),
        migrations.CreateModel(
            name='Historia_Clinica',
            fields=[
                ('Consecutivo', models.AutoField(primary_key=True, serialize=False)),
                ('Diagnostico', models.CharField(max_length=45)),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academical.Paciente')),
                ('ID_PS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academical.Personal')),
                ('ID_SV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academical.SignosVitales')),
            ],
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('Consecutivo_Cita', models.AutoField(primary_key=True, serialize=False)),
                ('Especialidad', models.CharField(max_length=45)),
                ('Motivo', models.CharField(max_length=45)),
                ('Fecha_Hora', models.DateTimeField()),
                ('Consecutivo_HC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academical.Historia_Clinica')),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academical.Paciente')),
                ('ID_PS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academical.Personal')),
            ],
        ),
    ]
