# Generated by Django 3.0.7 on 2022-09-09 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academical', '0005_auto_20220908_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='signosvitales',
            name='temperatura',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='historia_clinica',
            name='Diagnostico',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('Consecutivo', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=200)),
                ('Fecha_registro', models.DateTimeField()),
                ('Consecutivo_HC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academical.Historia_Clinica')),
            ],
        ),
    ]
